[project]
name = "shogihome-lan-engine-wrapper"
version = "1.2.1"
description = "USI Engine wrapper for ShogiHome LAN (Python version)"
requires-python = ">=3.10"
dependencies = [
    "python-dotenv>=1.0.1",
]

[dependency-groups]
dev = [
    "nuitka>=2.4.8",
    "pip-licenses>=5.0.0",
]
